version: "3.8"

services:
  api-gateway:
    build:
      context: . 
      dockerfile: apps/api-gateway/Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    working_dir: /apps/api-gateway
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
    networks:
      - app-network
    restart: unless-stopped
    # production: do not mount source (it would hide files in image)
    volumes:
      - ./logs:/apps/api-gateway/logs
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --show-error http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
